function jxTraceState(state) {
	var jsonObj = {
			1503:"二维码支付",
			2616:"提现(银联待收)",
			2703:"批量到期还款(手续费)",
			2748:"批量融资扣款(手续费)",
			2780:"批量融资扣款(投标扣款)",
			2781:"批量到期还款(到期还款)",
			2788:"批量代偿",
			2789:"批量债权转让(承接人扣款)",
			2792:"批量红包发放(平台红包账户扣款)",
			2793:"批量红包发放(平台红包账户加息扣款)",
			2820:"提现(行内/二代)",
			2821:"超级网银渠道转出",
			2822:"提现(cp代付)",
			2823:"行内卡渠道转出",
			2826:"大额渠道转出",
			2831:"联机债权转让",
			2833:"联机投标交易",
			2841:"联机投标实时划扣",
			2849:"联机手续费分账交易",
			2869:"联机满标放款(借款人手续费出账)",
			2883:"联机跨产品转账,资金转出",
			2938:"小额渠道转出",
			2939:"同城渠道转出",
			4616:"提现转账手续费",
			4780:"批量融资扣款手续费",
			4781:"批量到期还款手续费",
			4788:"批量代偿手续费",
			4820:"提现中间业务转出手续费",
			4822:"提现手续费",
			5500:"活期存款利息入账",
			5504:"靠档存款利息入账",
			7610:"线下充值银联同城柜面转入",
			7611:"线下充值银联同城ATM转入",
			7612:"线下充值银联异地柜面转入",
			7613:"线下充值银联异地ATM转入",
			7616:"充值交易",
			7617:"线下充值银联贷记交易",
			7710:"批量调账二代来账补账(调增)",
			7712:"批量调账CP代付补账",
			7722:"手续费入账",
			7724:"提现平台手续费账户入账",
			7725:"债权转让平台手续费账户入账",
			7777:"基金分红交易",
			7780:"批量融资扣款借款人资金入账",
			7781:"批量到期还款投资人资金入账",
			7782:"账户批量充值",
			7783:"账户红包发放",
			7785:"批量债权转让转让人资金入账",
			7788:"批量代偿投资人资金入账",
			7792:"批量红包发放红包",
			7793:"批量红包发放加息券收益",
			7820:"充值行内渠道资金转入",
			7821:"超级网银渠道转入",
			7822:"充值CP渠道",
			7823:"行内卡渠道转入",
			7826:"大额渠道转入",
			7831:"联机债权转让转让人资金入账",
			7833:"联机投标投资人红包入账",
			7835:"债权转让手续费转入",
			7838:"联机满标放款借款人电子账户入账",
			7849:"资金转入",
			7882:"投标撤销",
			7883:"资金转入",
			7901:"充值中金渠道",
			7905:"充值易宝渠道",
			7906:"充值快钱渠道",
			7907:"充值银盛渠道",
			7909:"充值浙江银商渠道",
			7910:"充值金运通渠道",
			7914:"联动优势",
			7917:"充值行内支付通道资金转入",
			7938:"小额渠道转入",
			7939:"同城渠道转入",
			9780:"批量融资扣款借款人手续费出账",
			9781:"批量到期还款投资人手续费出账",
			9785:"批量债权转让转让人手续费出账",
			9788:"批量代偿投资人手续费出账",
			9831:"联机债权转让转让人手续费出账",
			7996:"圈存",
			2996:"圈提",
		
	};
	for (var prop in jsonObj) {
		if (state == prop) {
			return jsonObj[prop];
		}
	}
	return state;
}

function jxTxCodeValue(jxTxCode){
	var jsonObj ={
			"smsCodeApply":"请求短信验证",
		    "accountOpenPage":"开户",
		    "passwordSet":"密码设置",
		    "passwordResetPlus":"密码重置增强",
		    "cardBindPlus":"绑定银行卡",
		    "bindCardPage":"绑定银行卡1.3",
		    "cardUnbind":"解绑银行卡",
		    "mobileModifyPlus":"电子账户手机号修改增强",
		    "directRechargePage":"充值",
		    "offlineRechargeCall":"线下充值回调",
		    "debtRegister":"借款人标的登记",
		    "debtRegisterCancel":"借款人标的撤销",
		    "bidApply":"投资人投标申请",
		    "autoBidAuthPlus":"自动投标签约",
		    "autoBidAuthCancel":"撤销自动投标签约",
		    "bidAutoApply":"自动投标申请",
		    "bidCancel":"投标申请撤销",
		    "autoCreditInvestAuthPlus":"自动债权转让签约增强",
		    "autoCreditInvestAuthCancel":"撤销自动债权转让签约",
		    "withdraw":"提现",
		    "withdrawcashReverseCall":"提现冲正",
		    "creditInvest":"投资人购买债权",
		    "voucherPay":"红包发放",
		    "voucherPayCancel":"红包发放撤销",
		    "voucherPayDelayCancel":"红包发放隔日撤销",
		    "batchLendPay":"批次放款",
		    "batchRepay":"批次还款",
		    "batchCreditEnd":"批次结束债权",
		    "batchCancel":"批次撤销",
		    "batchCreditInvest":"批次投资人购买债权",
		    "batchVoucherPay":"批次发红包",
		    "batchSubstRepay":"批次代偿",
		    "paymentAuthPage":"缴费授权",
		    "repayAuthPage":"还款授权",
		    "repayAuthCancel":"还款授权解约",
		    "paymentAuthCancel":"缴费授权解约",
		    "balanceFreeze":"还款申请冻结资金",
		    "balanceUnfreeze":"申请撤销资金解冻",
		    "refinanceFreezePage":"代偿冻结",
		    "balanceQuery":"余额查询",
		    "freezeAmtQuery":"冻结金额查询",
		    "accountDetailsQuery2":"资金交易明细查询",
		    "creditDetailsQuery":"债权明细查询",
		    "cardBindDetailsQuery":"绑卡查询",
		    "accountIdQuery":"证件号查电子账号",
		    "debtDetailsQuery":"借款人标的信息查询",
		    "mobileMaintainace":"查询手机号",
		    "accountQueryByMobile":"手机号查电子账号",
		    "transactionStatusQuery":"查询交易状态",
		    "batchQuery":"查询批次状态",
		    "batchDetailsQuery":"查询批次交易明细状态",
		    "creditInvestQuery":"购买债权查询",
		    "bidApplyQuery":"投标申请查询",
		    "creditAuthQuery":"签约状态查询",
		    "corprationQuery":"企业状态查询",
		    "frzDetailsQuery":"资金冻结明细查询",
		    "passwordSetQuery":"是否设置密码查询",
		    "balanceFreezeQuery":"单笔还款申请冻结查询",
		    "batchVoucherDetailsQuery":"查询批次发红包交易明细",
		    "fundTransQuery":"单笔资金类业务交易查询",
		    "creditInvesDetailsQuery":"债权转让明细查询",
		    "termsAuthQuery":"授权功能查询",
		    "creditForUnloadPage":"圈提",
		    "creditForLoadPage":"圈存",
	};
	for (var prop in jsonObj){
		if(jxTxCode == prop){
			return jsonObj[prop];
		}
	}
	return jxTxCode;
}

function jxState() {
	var jxArray = [ 1503, 2616, 2703, 2748, 2780, 2781, 2788, 2789, 2792, 2793,
			2820, 2821, 2822, 2823, 2826, 2831, 2833, 2841, 2849, 2869, 2883,
			2938, 2939, 4616, 4780, 4781, 4788, 4820, 4822, 5500, 5504, 7610,
			7611, 7612, 7613, 7616, 7617, 7710, 7712, 7722, 7724, 7725, 7777,
			7780, 7781, 7782, 7783, 7785, 7788, 7792, 7793, 7820, 7821, 7822,
			7823, 7826, 7831, 7833, 7835, 7838, 7849, 7882, 7883, 7901, 7905,
			7906, 7907, 7909, 7910, 7914, 7917, 7938, 7939, 9780, 9781, 9785,
			9788, 9831, 7996, 2996 ];
	return jxArray;
}

function txCode(){
	var jxTxCodeArray = [
	    "smsCodeApply",
	    "accountOpenPage",
	    "passwordSet",
	    "passwordResetPlus",
	    "cardBindPlus",
	    "bindCardPage",
	    "cardUnbind",
	    "mobileModifyPlus",
	    "directRechargePage",
	    "offlineRechargeCall",
	    "debtRegister",
	    "debtRegisterCancel",
	    "bidApply",
	    "autoBidAuthPlus",
	    "autoBidAuthCancel",
	    "bidAutoApply",
	    "bidCancel",
	    "autoCreditInvestAuthPlus",
	    "autoCreditInvestAuthCancel",
	    "withdraw",
	    "withdrawcashReverseCall",
	    "creditInvest",
	    "voucherPay",
	    "voucherPayCancel",
	    "voucherPayDelayCancel",
	    "batchLendPay",
	    "batchRepay",
	    "batchCreditEnd",
	    "batchCancel",
	    "batchCreditInvest",
	    "batchVoucherPay",
	    "batchSubstRepay",
	    "paymentAuthPage",
	    "repayAuthPage",
	    "repayAuthCancel",
	    "paymentAuthCancel",
	    "balanceFreeze",
	    "balanceUnfreeze",
	    "refinanceFreezePage",
	    "balanceQuery",
	    "freezeAmtQuery",
	    "accountDetailsQuery2",
	    "creditDetailsQuery",
	    "cardBindDetailsQuery",
	    "accountIdQuery",
	    "debtDetailsQuery",
	    "mobileMaintainace",
	    "accountQueryByMobile",
	    "transactionStatusQuery",
	    "batchQuery",
	    "batchDetailsQuery",
	    "creditInvestQuery",
	    "bidApplyQuery",
	    "creditAuthQuery",
	    "corprationQuery",
	    "frzDetailsQuery",
	    "passwordSetQuery",
	    "balanceFreezeQuery",
	    "batchVoucherDetailsQuery",
	    "fundTransQuery",
	    "creditInvesDetailsQuery",
	    "termsAuthQuery",
	    "creditForUnloadPage",
	    "creditForLoadPage"
	                     ];
	return jxTxCodeArray;
}
